name: Release Github zip

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout
        uses: actions/checkout@v2

      - uses: vimtor/action-zip@v1
        with:
          files: /assets /dist /includes /languages /vendor depay-woocommerce-payments LICENSE README.md readme.txt
          dest: depay-woocommerce-payments.zip
          recursive: false
      
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: depay-woocommerce-payments.zip
