name: Release Github zip

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      
      - name: Checkout
        uses: actions/checkout@v2

      - name: move files into dedicated folder /depay-woocommerce-payments
        run: |
          mkdir depay-woocommerce-payments && mv -t depay-woocommerce-payments depay-woocommerce-payments.php LICENSE readme.txt changelog.txt assets dist includes languages vendor

      - uses: montudor/action-zip@v1
        with:
          args: zip -qq -r depay-woocommerce-payments.zip depay-woocommerce-payments
      
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: depay-woocommerce-payments.zip
